"""autogenerate initial
Revision ID: 87d33473f8b1
Revises: 0001_initial
Create Date: 2025-12-26 20:37:37
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87d33473f8b1"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: FTS virtual tables are managed separately (sqlite FTS5 module). This
    # migration avoids dropping FTS tables and adds guards so it can run safely
    # (best-effort) against an existing SQLite DB that may have FTS virtual
    # tables/triggers installed.
    bind = op.get_bind()

    def table_exists(name: str) -> bool:
        try:
            r = bind.execute(
                sa.text(
                    "SELECT name FROM sqlite_master WHERE type='table' AND name=:name"
                ),
                {"name": name},
            ).fetchone()
            return bool(r)
        except Exception:
            return False

    def index_exists(table: str, index_name: str) -> bool:
        try:
            rows = list(bind.execute(sa.text(f"PRAGMA index_list('{table}')")))
        except Exception:
            return False
        for row in rows:
            if len(row) > 1 and row[1] == index_name:
                return True
        return False

    def fk_exists(table: str, fk_from: str, fk_table: str, fk_to: str) -> bool:
        try:
            rows = list(bind.execute(sa.text(f"PRAGMA foreign_key_list('{table}')")))
        except Exception:
            return False
        for r in rows:
            if len(r) >= 5 and r[2] == fk_table and r[3] == fk_from and r[4] == fk_to:
                return True
        return False

    # defensive cleanup: remove leftover temp tables from previous failed runs
    try:
        tmp_tables = [
            r[0]
            for r in bind.execute(
                sa.text(
                    "SELECT name FROM sqlite_master WHERE name LIKE '_alembic_tmp%';"
                )
            ).fetchall()
        ]
        for t in tmp_tables:
            try:
                bind.execute(sa.text(f"DROP TABLE IF EXISTS {t};"))
            except Exception:
                pass
    except Exception:
        pass

    # Alter 'comments' table with SQLite-safe batch operation, skip on failure
    try:
        with op.batch_alter_table("comments") as batch_op:
            batch_op.alter_column(
                "is_moderated", existing_type=sa.BOOLEAN(), nullable=False
            )
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=False
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'comments' table due to: {e}")

    # Create index if missing
    try:
        if not index_exists("comments", "ix_comments_idea_moderated"):
            op.create_index(
                "ix_comments_idea_moderated",
                "comments",
                ["idea_id", "is_moderated"],
                unique=False,
            )
    except Exception as e:
        print(f"WARNING: Skipping creating index ix_comments_idea_moderated: {e}")

    try:
        with op.batch_alter_table("idea_tags") as batch_op:
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=False
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'idea_tags' table due to: {e}")

    try:
        with op.batch_alter_table("ideas") as batch_op:
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=False
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'ideas' table due to: {e}")

    # Add indexes for 'ideas' safely
    try:
        if not index_exists("ideas", "ix_ideas_category"):
            op.create_index("ix_ideas_category", "ideas", ["category_id"], unique=False)
        if not index_exists("ideas", "ix_ideas_status"):
            op.create_index("ix_ideas_status", "ideas", ["status"], unique=False)
        if not index_exists("ideas", "ix_ideas_user_status"):
            op.create_index(
                "ix_ideas_user_status", "ideas", ["user_id", "status"], unique=False
            )
    except Exception as e:
        print(f"WARNING: Skipping some 'ideas' indexes due to: {e}")

    # Add foreign key 'deleted_by' -> users(id) if not present
    try:
        if not fk_exists("ideas", "deleted_by", "users", "id"):
            try:
                op.create_foreign_key(None, "ideas", "users", ["deleted_by"], ["id"])
            except Exception as e:
                print(f"WARNING: Couldn't create FK on 'ideas.deleted_by': {e}")
    except Exception:
        pass

    try:
        with op.batch_alter_table("tags") as batch_op:
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=False
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'tags' table due to: {e}")

    try:
        with op.batch_alter_table("users") as batch_op:
            batch_op.alter_column(
                "is_global_admin", existing_type=sa.BOOLEAN(), nullable=False
            )
            batch_op.alter_column(
                "is_active", existing_type=sa.BOOLEAN(), nullable=False
            )
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=False
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'users' table due to: {e}")

    try:
        with op.batch_alter_table("votes") as batch_op:
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=False
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'votes' table due to: {e}")

    # Create votes indexes if missing
    try:
        if not index_exists("votes", "ix_votes_idea"):
            op.create_index("ix_votes_idea", "votes", ["idea_id"], unique=False)
        if not index_exists("votes", "ix_votes_user_idea"):
            op.create_index(
                "ix_votes_user_idea", "votes", ["user_id", "idea_id"], unique=False
            )
    except Exception as e:
        print(f"WARNING: Skipping creating votes indexes due to: {e}")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    def index_exists(table: str, index_name: str) -> bool:
        try:
            rows = list(bind.execute(sa.text(f"PRAGMA index_list('{table}')")))
        except Exception:
            return False
        for row in rows:
            if len(row) > 1 and row[1] == index_name:
                return True
        return False

    def table_exists(name: str) -> bool:
        try:
            r = bind.execute(
                sa.text(
                    "SELECT name FROM sqlite_master WHERE type='table' AND name=:name"
                ),
                {"name": name},
            ).fetchone()
            return bool(r)
        except Exception:
            return False

    # Drop votes indexes if they exist
    try:
        if index_exists("votes", "ix_votes_user_idea"):
            op.drop_index("ix_votes_user_idea", table_name="votes")
        if index_exists("votes", "ix_votes_idea"):
            op.drop_index("ix_votes_idea", table_name="votes")
    except Exception as e:
        print(f"WARNING: Skipping dropping votes indexes due to: {e}")

    # Restore nullable columns where possible
    try:
        with op.batch_alter_table("votes") as batch_op:
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=True
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'votes' table during downgrade: {e}")

    try:
        with op.batch_alter_table("users") as batch_op:
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=True
            )
            batch_op.alter_column(
                "is_active", existing_type=sa.BOOLEAN(), nullable=True
            )
            batch_op.alter_column(
                "is_global_admin", existing_type=sa.BOOLEAN(), nullable=True
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'users' table during downgrade: {e}")

    try:
        with op.batch_alter_table("tags") as batch_op:
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=True
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'tags' table during downgrade: {e}")

    # Try to drop foreign key on ideas, but ignore errors (names vary by DB)
    try:
        try:
            op.drop_constraint(None, "ideas", type_="foreignkey")  # type: ignore[arg-type]
        except Exception:
            # best-effort: can't reliably find constraint name for sqlite
            pass
    except Exception as e:
        print(f"WARNING: Skipping dropping FK on 'ideas' during downgrade: {e}")

    # Drop idea indexes if present
    try:
        if index_exists("ideas", "ix_ideas_user_status"):
            op.drop_index("ix_ideas_user_status", table_name="ideas")
        if index_exists("ideas", "ix_ideas_status"):
            op.drop_index("ix_ideas_status", table_name="ideas")
        if index_exists("ideas", "ix_ideas_category"):
            op.drop_index("ix_ideas_category", table_name="ideas")
    except Exception as e:
        print(f"WARNING: Skipping dropping some 'ideas' indexes due to: {e}")

    try:
        with op.batch_alter_table("ideas") as batch_op:
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=True
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'ideas' table during downgrade: {e}")

    try:
        with op.batch_alter_table("idea_tags") as batch_op:
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=True
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'idea_tags' during downgrade: {e}")

    # Drop comment index and revert columns
    try:
        if index_exists("comments", "ix_comments_idea_moderated"):
            op.drop_index("ix_comments_idea_moderated", table_name="comments")
    except Exception as e:
        print(f"WARNING: Skipping dropping comment index due to: {e}")

    try:
        with op.batch_alter_table("comments") as batch_op:
            batch_op.alter_column(
                "created_at", existing_type=sa.DATETIME(), nullable=True
            )
            batch_op.alter_column(
                "is_moderated", existing_type=sa.BOOLEAN(), nullable=True
            )
    except Exception as e:
        print(f"WARNING: Skipping altering 'comments' table during downgrade: {e}")

    # NOTE: FTS virtual tables were not managed in this migration. If you rely
    # on these structures, recreate them using the project's fts setup scripts
    # or by manual SQL that ensures the proper SQLite extensions are present.
    # ### end Alembic commands ###
