#!/bin/bash
# Switch between platform instances
# Usage: ./scripts/switch-instance.sh [instance-name]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
INSTANCES_DIR="$PROJECT_ROOT/instances"
FRONTEND_DIR="$PROJECT_ROOT/frontend"
BACKEND_DIR="$PROJECT_ROOT/backend"
INSTANCE_ASSETS_DIR="$FRONTEND_DIR/public/instance"

# Get list of available instances
get_instances() {
  for dir in "$INSTANCES_DIR"/*/; do
    [ -d "$dir" ] && [ -f "$dir/platform.config.json" ] && basename "$dir"
  done
}

# Check if instance exists
instance_exists() {
  [ -f "$INSTANCES_DIR/$1/platform.config.json" ]
}

# Extract value from JSON using python (more portable than jq)
json_get() {
  python3 -c "import json; d=json.load(open('$1')); print(d$2)" 2>/dev/null
}

clean_frontend_cache() {
  echo "Cleaning frontend caches..."

  if [ -d "$FRONTEND_DIR/.next" ]; then
    rm -rf "$FRONTEND_DIR/.next" 2>/dev/null && echo "  - Removed .next/" || {
      echo "  - Warning: Could not remove .next/ (stop pnpm dev first)"
    }
  fi

  if [ -d "$FRONTEND_DIR/node_modules/.cache" ]; then
    rm -rf "$FRONTEND_DIR/node_modules/.cache"
    echo "  - Removed node_modules/.cache/"
  fi
}

clean_instance_assets() {
  echo "Cleaning instance assets..."
  if [ -d "$INSTANCE_ASSETS_DIR" ]; then
    rm -rf "$INSTANCE_ASSETS_DIR"
    echo "  - Removed public/instance/"
  fi
}

switch_instance() {
  local instance="$1"
  local config_path="$INSTANCES_DIR/$instance/platform.config.json"
  local images_path="$INSTANCES_DIR/$instance/images"

  if [ ! -f "$config_path" ]; then
    echo "Error: Instance '$instance' not found"
    echo ""
    show_usage
    exit 1
  fi

  echo "=== Switching to $instance instance ==="
  echo ""

  # Get database file from config
  local db_file=$(json_get "$config_path" "['database']['file']")
  if [ -z "$db_file" ]; then
    echo "Error: Could not read database.file from config"
    exit 1
  fi

  # Frontend setup
  echo "[Frontend]"
  clean_frontend_cache
  clean_instance_assets

  echo ""
  echo "Copying assets..."
  mkdir -p "$INSTANCE_ASSETS_DIR"

  if [ -d "$images_path" ]; then
    cp -r "$images_path/"* "$INSTANCE_ASSETS_DIR/"
    echo "  - Copied images to public/instance/"
  fi

  # Backend setup
  echo ""
  echo "[Backend]"

  # Symlink active config
  rm -f "$BACKEND_DIR/config/platform.config.active.json"
  ln -s "$config_path" "$BACKEND_DIR/config/platform.config.active.json"
  echo "  - Linked config: instances/$instance/platform.config.json"

  # Create .env.instance with exported vars
  cat > "$BACKEND_DIR/.env.instance" << EOF
# Instance: $instance
# Generated by switch-instance.sh - do not edit directly
export PLATFORM_CONFIG_PATH=$config_path
export DATABASE_URL=sqlite:///./data/$db_file
EOF
  echo "  - Created .env.instance"
  echo "  - Database: $db_file"

  # Update root .env file for Docker
  if [ -f "$PROJECT_ROOT/.env" ]; then
    # Update PLATFORM_CONFIG_PATH
    if grep -q "^PLATFORM_CONFIG_PATH=" "$PROJECT_ROOT/.env"; then
      sed -i "s|^PLATFORM_CONFIG_PATH=.*|PLATFORM_CONFIG_PATH=/instances/$instance/platform.config.json|" "$PROJECT_ROOT/.env"
    else
      echo "PLATFORM_CONFIG_PATH=/instances/$instance/platform.config.json" >> "$PROJECT_ROOT/.env"
    fi
    # Update ACTIVE_INSTANCE
    if grep -q "^ACTIVE_INSTANCE=" "$PROJECT_ROOT/.env"; then
      sed -i "s|^ACTIVE_INSTANCE=.*|ACTIVE_INSTANCE=$instance|" "$PROJECT_ROOT/.env"
    else
      echo "ACTIVE_INSTANCE=$instance" >> "$PROJECT_ROOT/.env"
    fi

    # Update DATABASE_URL (only the non-commented one)
    if grep -q "^DATABASE_URL=" "$PROJECT_ROOT/.env"; then
      sed -i "s|^DATABASE_URL=sqlite:///.*|DATABASE_URL=sqlite:///./data/$db_file|" "$PROJECT_ROOT/.env"
    fi

    # Update Docker container naming based on instance
    local container_prefix=""
    local compose_name=""
    case "$instance" in
      montreal)
        container_prefix="idees-mtl"
        compose_name="idees-montreal"
        ;;
      quebec)
        container_prefix="idees-qc"
        compose_name="idees-quebec"
        ;;
      calgary)
        container_prefix="ideas-cgy"
        compose_name="ideas-calgary"
        ;;
      *)
        container_prefix="ocv-$instance"
        compose_name="opencitivibes-$instance"
        ;;
    esac

    # Update CONTAINER_PREFIX
    if grep -q "^CONTAINER_PREFIX=" "$PROJECT_ROOT/.env"; then
      sed -i "s|^CONTAINER_PREFIX=.*|CONTAINER_PREFIX=$container_prefix|" "$PROJECT_ROOT/.env"
    else
      echo "CONTAINER_PREFIX=$container_prefix" >> "$PROJECT_ROOT/.env"
    fi
    # Update COMPOSE_PROJECT_NAME
    if grep -q "^COMPOSE_PROJECT_NAME=" "$PROJECT_ROOT/.env"; then
      sed -i "s|^COMPOSE_PROJECT_NAME=.*|COMPOSE_PROJECT_NAME=$compose_name|" "$PROJECT_ROOT/.env"
    else
      echo "COMPOSE_PROJECT_NAME=$compose_name" >> "$PROJECT_ROOT/.env"
    fi

    echo "  - Updated .env for Docker (prefix: $container_prefix)"
  fi

  # Record active instance for status checks
  echo "$instance" > "$PROJECT_ROOT/.active-instance"

  echo ""
  echo "=== Switched to $instance ==="
  echo ""
  echo "Start servers:"
  echo "  ./scripts/start-dev.sh"
  echo ""
  echo "Or manually:"
  echo "  Backend:  cd backend && source .env.instance && uv run uvicorn main:app --reload --port 8000"
  echo "  Frontend: cd frontend && pnpm dev"
}

show_status() {
  echo "Current instance:"
  if [ -f "$PROJECT_ROOT/.active-instance" ]; then
    echo "  $(cat "$PROJECT_ROOT/.active-instance")"
  else
    echo "  None configured"
  fi

  echo ""
  echo "Available instances:"
  for instance in $(get_instances); do
    local config="$INSTANCES_DIR/$instance/platform.config.json"
    local name=$(json_get "$config" "['instance']['name']['en']")
    echo "  - $instance: $name"
  done
}

show_usage() {
  echo "Usage: $0 [instance|clean|status]"
  echo ""
  echo "Instances:"
  for instance in $(get_instances); do
    echo "  $instance"
  done
  echo ""
  echo "Commands:"
  echo "  clean   - Clean all caches and instance assets"
  echo "  status  - Show current instance and available instances"
}

# Main
case "$1" in
  ""|help|-h|--help)
    show_usage
    ;;
  clean)
    clean_frontend_cache
    clean_instance_assets
    echo "Done."
    ;;
  status)
    show_status
    ;;
  *)
    if instance_exists "$1"; then
      switch_instance "$1"
    else
      echo "Error: Unknown instance '$1'"
      echo ""
      show_usage
      exit 1
    fi
    ;;
esac
